,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/47610,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47610/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47610/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47610/events,https://github.com/pandas-dev/pandas/issues/47610,1295757814,I_kwDOAA0YD85NO7H2,47610,BUG: Pandas refuses to convert object type to string,"{'login': 'steve-solun', 'id': 108329117, 'node_id': 'U_kgDOBnT4nQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/108329117?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/steve-solun', 'html_url': 'https://github.com/steve-solun', 'followers_url': 'https://api.github.com/users/steve-solun/followers', 'following_url': 'https://api.github.com/users/steve-solun/following{/other_user}', 'gists_url': 'https://api.github.com/users/steve-solun/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/steve-solun/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/steve-solun/subscriptions', 'organizations_url': 'https://api.github.com/users/steve-solun/orgs', 'repos_url': 'https://api.github.com/users/steve-solun/repos', 'events_url': 'https://api.github.com/users/steve-solun/events{/privacy}', 'received_events_url': 'https://api.github.com/users/steve-solun/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-06T12:20:22Z,2022-07-06T12:20:22Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

my_dict = my_dict = {'content': {'0': '{\n ""metadata"": {\n  ""name"": """"\n },\n ""nbformat"": 3,\n ""nbformat_minor"": 0,\n ""worksheets"": [\n  {\n   ""cells"": [\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [\n      ""import klustaviewa.dataio as kvio""\n     ],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": [],\n     ""prompt_number"": 1\n    },\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [\n      ""fet_filename = r\\""D:\\\\Spike sorting\\\\sirota\\\\ec016.694_711.fet.7\\""\\n"",\n      ""spk_filename = r\\""D:\\\\Spike sorting\\\\sirota\\\\ec016.694_711.spk.7\\""""\n     ],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": [],\n     ""prompt_number"": 2\n    },\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [\n      ""fet = kvio.MemMappedText(fet_filename, np.int16, skiprows=1)""\n     ],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": [],\n     ""prompt_number"": 3\n    },\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [\n      ""%timeit -n 100 -r 1 [fet.next() for _ in xrange(1000)]""\n     ],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": [\n      {\n       ""output_type"": ""stream"",\n       ""stream"": ""stdout"",\n       ""text"": [\n        ""100 loops, best of 1: 3.62 ms per loop\\n""\n       ]\n      }\n     ],\n     ""prompt_number"": 4\n    },\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [\n      ""spk = kvio.MemMappedBinary(spk_filename, np.int16, 89*32)""\n     ],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": [],\n     ""prompt_number"": 5\n    },\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [\n      ""%timeit -n 100 -r 1 [spk.next() for _ in xrange(1000)]""\n     ],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": [\n      {\n       ""output_type"": ""stream"",\n       ""stream"": ""stdout"",\n       ""text"": [\n        ""100 loops, best of 1: 10.5 ms per loop\\n""\n       ]\n      }\n     ],\n     ""prompt_number"": 6\n    },\n    {\n     ""cell_type"": ""code"",\n     ""collapsed"": false,\n     ""input"": [],\n     ""language"": ""python"",\n     ""metadata"": {},\n     ""outputs"": []\n    }\n   ],\n   ""metadata"": {}\n  }\n ]\n}',
      '1': '{\n ""cells"": [\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""# Scraping Reviews #\\n"",\n    ""\\n"",\n    ""This notebook shows how to use the scrape reviews from Indeed and Glassdoor. To visualize the ratings go to the [Ratings](Ratings.html) notebook and to do topic modeling go to the [Topic Modeling](Topic-Modeling.html) notebook.\\n"",\n    ""\\n"",\n    ""Before, make sure you have MongoDB up and running.""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""## Parameters ##""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": 1,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""# Search settings\\n"",\n    ""KEYWORD_FILTER = \\""Data Scientist\\""\\n"",\n    ""LOCATION_FILTER = \\""New York City, NY\\""\\n"",\n    ""\\n"",\n    ""# Other settings\\n"",\n    ""MAX_PAGES_COMPANIES = 500\\n"",\n    ""MAX_PAGES_REVIEWS = 500""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": 14,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""import os\\n"",\n    ""import re\\n"",\n    ""from datetime import datetime\\n"",\n    ""from pymongo import MongoClient\\n"",\n    ""import indeed\\n"",\n    ""import glassdoor\\n"",\n    ""import utils""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": 4,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""# DB settings\\n"",\n    ""client = MongoClient()\\n"",\n    ""indeed_db = client.indeed\\n"",\n    ""indeed_jobs = indeed_db.jobs\\n"",\n    ""indeed_reviews = indeed_db.reviews\\n"",\n    ""glassdoor_db = client.glassdoor\\n"",\n    ""glassdoor_reviews = glassdoor_db.reviews""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""## Scrape job listings from Indeed ##""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""jobs = indeed.get_jobs(KEYWORD_FILTER, LOCATION_FILTER, indeed_jobs, MAX_PAGES_COMPANIES)""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""## Scrape company reviews from Indeed ##\\n"",\n    ""\\n"",\n    ""This takes all the companies that appear in the jobs scraped.""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""indeed.get_all_company_reviews(jobs, indeed_reviews, MAX_PAGES_REVIEWS)""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": 5,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [\n    {\n     ""data"": {\n      ""text/plain"": [\n       ""{u\'_id\': ObjectId(\'54f763e3bcccd9197dbbdb91\'),\\n"",\n       "" u\'company_name\': u\'American Express\',\\n"",\n       "" u\'date\': datetime.datetime(2013, 4, 3, 0, 0),\\n"",\n       "" u\'employment_status\': u\'\\\\xa0(Former Employee),\\\\xa0\',\\n"",\n       "" u\'job_title\': u\'Shipping Clerk\',\\n"",\n       "" u\'location\': u\'Piscataway, New Jersey\',\\n"",\n       "" u\'rating\': u\'5.0\',\\n"",\n       "" u\'review_cons\': u\'Cons: long hours doing the christmas season\',\\n"",\n       "" u\'review_pros\': u\'Pros: you are able to apply for a credit card\',\\n"",\n       "" u\'review_text\': u\'If you are looking for a job to retire from and the work is not hard,then American Express is that company.\',\\n"",\n       "" u\'review_title\': u\'A Company with a future\',\\n"",\n       "" u\'stars\': {u\'Compensation/Benefits\': 5,\\n"",\n       ""  u\'Job Culture\': 5,\\n"",\n       ""  u\'Job Security/Advancement\': 5,\\n"",\n       ""  u\'Job Work/Life Balance\': 5,\\n"",\n       ""  u\'Management\': 5}}""\n      ]\n     },\n     ""execution_count"": 5,\n     ""metadata"": {},\n     ""output_type"": ""execute_result""\n    }\n   ],\n   ""source"": [\n    ""indeed_reviews.find_one()""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""# Fix Company Names #\\n"",\n    ""\\n"",\n    ""Indeed\'s company names are inconsistent. The same company can be listed several times with various spellings/typos/words. It\'s necessary to look at the companies and fix the names. The utils module has a function which takes a dictionary that takes the old name and returns the new one (names not in the dictionary are left as is). See below for an example (the one I used had over 30 name fixes.""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": 17,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [\n    {\n     ""data"": {\n      ""text/plain"": [\n       ""[u\'Financial Times\',\\n"",\n       "" u\'McGraw Hill Financial\',\\n"",\n       "" u\'The Nielsen Company\',\\n"",\n       "" u\'Continuum\',\\n"",\n       "" u\'RUSSELL INVESTMENTS\']""\n      ]\n     },\n     ""execution_count"": 17,\n     ""metadata"": {},\n     ""output_type"": ""execute_result""\n    }\n   ],\n   ""source"": [\n    ""companies = list(set(utils.get_company_names(indeed_reviews)))\\n"",\n    ""companies[:5]""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""fix_companies = {\'Argus, ISO, Verisk Analytics, Verisk Climate, Veri...\': \'Verisk Analytics\',\\n"",\n    ""                 \'Barclays Investment Bank\': \'Barclays\', \'Dun & Brandstreet\': u\'Dun & Bradstreet\', \\n"",\n    ""                 \'Dun & Broadstreet\':u\'Dun & Bradstreet\', \'World Business Lenders - New York, NY\':\'World Business Lenders\'\\n"",\n    ""                }\\n"",\n    ""utils.fix_all_company_names(indeed_reviews, fix_companies)""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""companies = list(set(utils.get_company_names(indeed_reviews)))""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""## Scrape Glassdoor ##""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""visited_companies, failed_companies = glassdoor.get_all_company_reviews(companies, \\n"",\n    ""                                              glassdoor_reviews, MAX_PAGES_REVIEWS)""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""## Final Fixes ##\\n"",\n    ""\\n"",\n    ""Look at the failed companies. Often they couldn\'t be found on glassdoor because of an issue with their name. You might need to fix the names again (and search on glassdoor for the name some companies are listed under). Beware of encoding issues: if you pass an optional flag to utils.fix_company_name, you can encode the company names to ascii.\\n"",\n    ""\\n"",\n    ""Note: this is usually quite a bit slower than Indeed because there are many more reviews (e.g. Goldman Sachs has 198 pages!).""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""# fix_companies = {u\'SigmaTek\':u\'SigmaTek Consulting LLC\',\\n"",\n    ""#                 }\\n"",\n    ""# utils.fix_all_company_names(indeed_reviews, fix_companies)\\n"",\n    ""# fixed_failed_companies = fixed_failed_companies = [utils.fix_company_name(company,\\n"",\n    ""# fix_companies, True) for company in failed_companies]\\n"",\n    ""# visited_companies2, failed_companies = glassdoor.get_all_company_reviews(fixed_failed_companies, \\n"",\n    ""#                                               glassdoor_reviews, MAX_PAGES_REVIEWS)""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""Here I would do one last check too see which companies were scraped in glassdoor and indeed. Occasionally the wrong company might have been scraped on glassdoor.""\n   ]\n  },\n  {\n   ""cell_type"": ""code"",\n   ""execution_count"": null,\n   ""metadata"": {\n    ""collapsed"": false\n   },\n   ""outputs"": [],\n   ""source"": [\n    ""glassdoor_companies = set(utils.get_company_names(glassdoor_reviews))\\n"",\n    ""indeed_companies = set(utils.get_company_names(indeed_reviews))\\n"",\n    ""\\n"",\n    ""# Remove the extra companies:\\n"",\n    ""extra_companies = glassdoor_companies - indeed_companies\\n"",\n    ""for company in extra_companies:\\n"",\n    ""    glassdoor_reviews.remove({\'company\' : company})\\n"",\n    ""\\n"",\n    ""print \\""Missing companies\\"", indeed_companies - glassdoor_companies""\n   ]\n  },\n  {\n   ""cell_type"": ""markdown"",\n   ""metadata"": {},\n   ""source"": [\n    ""## Done! ##\\n"",\n    ""Now all of the data is in the Mongo database. To visualize the ratings go to the [Ratings](Ratings.ipynb) notebook and to do topic modeling go to the [Topic Modeling](Topic Modeling.ipynb) notebook.""\n   ]\n  }\n ],\n ""metadata"": {\n  ""kernelspec"": {\n   ""display_name"": ""Python 2"",\n   ""language"": ""python"",\n   ""name"": ""python2""\n  },\n  ""language_info"": {\n   ""codemirror_mode"": {\n    ""name"": ""ipython"",\n    ""version"": 2\n   },\n   ""file_extension"": "".py"",\n   ""mimetype"": ""text/x-python"",\n   ""name"": ""python"",\n   ""nbconvert_exporter"": ""python"",\n   ""pygments_lexer"": ""ipython2"",\n   ""version"": ""2.7.9""\n  }\n },\n ""nbformat"": 4,\n ""nbformat_minor"": 0\n}\n'},
     'language': {'0': 'Jupyter Notebook', '1': 'Jupyter Notebook'}}

toy_df = pd.DataFrame.from_dict(my_dict)
toy_df.dtypes
toy_df.infer_objects().dtypes
toy_df.content.astype('str')

# Returns object dtype, not string
```


### Issue Description

For some reason I can't convert object dtype to str in pandas dataframe.

### Expected Behavior

I expect to be able to infer dtypes and/or convert object dtype to string.

### Installed Versions


INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.1.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47610/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47610/timeline,,,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/47609,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47609/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47609/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47609/events,https://github.com/pandas-dev/pandas/pull/47609,1295654303,PR_kwDOAA0YD8467XTi,47609,DOC: fix shared compression_options and decompression_options ,"{'login': 'alastair', 'id': 19217, 'node_id': 'MDQ6VXNlcjE5MjE3', 'avatar_url': 'https://avatars.githubusercontent.com/u/19217?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alastair', 'html_url': 'https://github.com/alastair', 'followers_url': 'https://api.github.com/users/alastair/followers', 'following_url': 'https://api.github.com/users/alastair/following{/other_user}', 'gists_url': 'https://api.github.com/users/alastair/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alastair/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alastair/subscriptions', 'organizations_url': 'https://api.github.com/users/alastair/orgs', 'repos_url': 'https://api.github.com/users/alastair/repos', 'events_url': 'https://api.github.com/users/alastair/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alastair/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-07-06T10:55:53Z,2022-07-06T11:55:10Z,,NONE,,"Both compression_options and decompression_options made the same
reference to zstandard.ZstdDecompressor however compression uses
zstandard.ZstdCompressor and so the documentation for
compression_options should refer to this class instead

The shared doc strings compression_options and decompression_options
require an interpolated string for the name of the parameter that takes
a filepath/buffer, with the name of this parameter.
It was missing in a few places.

Also fix a small gramatical error in compression_options

It took me a while to find the documentation for the python zstandard library to see what options are available to pass in as a dictionary, do you think it's worth updating the text `zstandard.ZstdDecompressor ` in the docs to be a link to https://python-zstandard.readthedocs.io/en/latest/decompressor.html?

I saw some test failures when running test_fast.sh inside the provided Docker image, but from what I can tell, these are not related to the changes that I made, and I also see the same failure when running tests from `main`:

<details>
  <summary>test failure</summary>
  
```
pandas/tests/test_expressions.py:133: AssertionError
________________ TestExpressions.test_run_binary[gt-False-df2] _________________
[gw2] linux -- Python 3.8.13 /opt/conda/bin/python

self = <pandas.tests.test_expressions.TestExpressions object at 0x7fcc8c9f3fd0>
df =         A   B   C   D
0       0   0  12   0
1      22  22  54  17
2       0   0  21   0
3       0  95   0   0
4       ...3  91
9997   25   0  32   5
9998    0  55   0  62
9999   42  25  30   1
10000   3   0  75  56

[10001 rows x 4 columns]
flex = False, comparison_op = <built-in function gt>

    @pytest.mark.parametrize(
        ""df"",
        [
            _integer,
            _integer2,
            # randint to get a case with zeros
            _integer * np.random.randint(0, 2, size=np.shape(_integer)),
            _frame,
            _frame2,
            _mixed,
            _mixed2,
        ],
    )
    @pytest.mark.parametrize(""flex"", [True, False])
    def test_run_binary(self, df, flex, comparison_op):
        """"""
        tests solely that the result is the same whether or not numexpr is
        enabled.  Need to test whether the function does the correct thing
        elsewhere.
        """"""
        arith = comparison_op.__name__
        with option_context(""compute.use_numexpr"", False):
            other = df.copy() + 1

        expr._MIN_ELEMENTS = 0
        expr.set_test_mode(True)

        result, expected = self.call_op(df, other, flex, arith)

        used_numexpr = expr.get_test_result()
>       assert used_numexpr, ""Did not use numexpr as expected.""
E       AssertionError: Did not use numexpr as expected.
E       assert []
```
</details>

- [x] no related ticket
- [x] Built and inspected docs
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] N/A Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] N/A Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47609/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47609/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47609', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47609', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47609.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47609.patch', 'merged_at': None}"
2,https://api.github.com/repos/pandas-dev/pandas/issues/47608,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47608/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47608/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47608/events,https://github.com/pandas-dev/pandas/issues/47608,1295610501,I_kwDOAA0YD85NOXKF,47608,BUG: inconsistent index between plain DataFrame and read_sql DataFrame,"{'login': 'jf2', 'id': 13077143, 'node_id': 'MDQ6VXNlcjEzMDc3MTQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/13077143?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jf2', 'html_url': 'https://github.com/jf2', 'followers_url': 'https://api.github.com/users/jf2/followers', 'following_url': 'https://api.github.com/users/jf2/following{/other_user}', 'gists_url': 'https://api.github.com/users/jf2/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jf2/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jf2/subscriptions', 'organizations_url': 'https://api.github.com/users/jf2/orgs', 'repos_url': 'https://api.github.com/users/jf2/repos', 'events_url': 'https://api.github.com/users/jf2/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jf2/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-07-06T10:19:15Z,2022-07-06T10:57:25Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import sqlite3

conn = sqlite3.connect("":memory:"")

cur = conn.cursor()
cur.execute(""CREATE TABLE data (id int, val real)"")
cur.execute(""INSERT INTO data VALUES (1, 150.0), (2, 160.0)"")
conn.commit()

full_df = pd.DataFrame({""id"": [1, 2], ""val"": [150.0, 160.0]})
full_sql_df = pd.read_sql(""SELECT * FROM data"", conn)

empty_df = pd.DataFrame({""id"": [], ""val"": []})
empty_sql_df = pd.read_sql(""SELECT * FROM data WHERE (1 = 0)"", conn)

pd.testing.assert_frame_equal(full_df, full_sql_df)
pd.testing.assert_frame_equal(empty_df, empty_sql_df)
```


### Issue Description

The empty DataFrame returned from read_sql has a different index type than if one constructs an empty DataFrame directly. When the returned SQL frame is not empty, the index types match.

### Expected Behavior

The returned empty SQL DataFrame's index is also a `RangeIndex(start=0, end=0, step=1)`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252
pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 58.2.0
pip              : 21.3
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47608/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47608/timeline,,,,
3,https://api.github.com/repos/pandas-dev/pandas/issues/47607,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47607/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47607/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47607/events,https://github.com/pandas-dev/pandas/issues/47607,1295265525,I_kwDOAA0YD85NNC71,47607,BUG: MultiIndex level not sorted (as desired) after making it a CategoricalIndex,"{'login': 'd-s-dc', 'id': 68206552, 'node_id': 'MDQ6VXNlcjY4MjA2NTUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/68206552?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/d-s-dc', 'html_url': 'https://github.com/d-s-dc', 'followers_url': 'https://api.github.com/users/d-s-dc/followers', 'following_url': 'https://api.github.com/users/d-s-dc/following{/other_user}', 'gists_url': 'https://api.github.com/users/d-s-dc/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/d-s-dc/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/d-s-dc/subscriptions', 'organizations_url': 'https://api.github.com/users/d-s-dc/orgs', 'repos_url': 'https://api.github.com/users/d-s-dc/repos', 'events_url': 'https://api.github.com/users/d-s-dc/events{/privacy}', 'received_events_url': 'https://api.github.com/users/d-s-dc/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}, {'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical', 'name': 'Categorical', 'color': 'e11d21', 'default': False, 'description': 'Categorical Data Type'}]",open,False,,[],,0,2022-07-06T06:39:25Z,2022-07-06T11:02:18Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

months = ['January','February','March','April','May','June','July','August','September','October','November','December']
df = pd.DataFrame({'col' : np.arange(1,25,1)},\
                  index = pd.MultiIndex.from_product([months, [1,2]], names = ['idx_1', 'idx_2'])).sort_index()
cidx = pd.CategoricalIndex(df.index.get_level_values(0).unique(), months, ordered = True)
df.index = df.index.set_levels(cidx, level = 0)
df = df.sort_index(level = 0)
display(df)
```


### Issue Description

I wanted to sort the months at _MultiIndex_ level0 according to real life scenario. So I used `CategoricalIndex` and assigned it to the level0 of the MultiIndex. What I expected after `sort_index` was that the level0 would be sorted using the _order defined in the CategoricalIndex_.
But even after making them as CategoricalIndex they are not sorted as expected.

### Expected Behavior

What I wanted is that months should be sorted according to the _given order in CategoricalIndex_

The expected behaviour can be produced by this code as follows
```
display(df.reindex(months, level = 0))
```
![image](https://user-images.githubusercontent.com/68206552/177484477-b6ae2994-8706-421a-9758-d4729a9061ff.png)


### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : 
sqlalchemy       : 1.4.32
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47607/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47607/timeline,,,,
4,https://api.github.com/repos/pandas-dev/pandas/issues/47606,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47606/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47606/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47606/events,https://github.com/pandas-dev/pandas/issues/47606,1295141155,I_kwDOAA0YD85NMkkj,47606,DOC: sample codes should not override Python built-in functions,"{'login': 'wany-oh', 'id': 98004396, 'node_id': 'U_kgDOBddtrA', 'avatar_url': 'https://avatars.githubusercontent.com/u/98004396?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/wany-oh', 'html_url': 'https://github.com/wany-oh', 'followers_url': 'https://api.github.com/users/wany-oh/followers', 'following_url': 'https://api.github.com/users/wany-oh/following{/other_user}', 'gists_url': 'https://api.github.com/users/wany-oh/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/wany-oh/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/wany-oh/subscriptions', 'organizations_url': 'https://api.github.com/users/wany-oh/orgs', 'repos_url': 'https://api.github.com/users/wany-oh/repos', 'events_url': 'https://api.github.com/users/wany-oh/events{/privacy}', 'received_events_url': 'https://api.github.com/users/wany-oh/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-06T05:06:43Z,2022-07-06T05:06:43Z,,NONE,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

For example, https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#transformation

> Alternatively, the built-in methods could be used to produce the same outputs.
> 
> ```python
> max = ts.groupby(lambda x: x.year).transform(""max"")
>
> min = ts.groupby(lambda x: x.year).transform(""min"")
> 
> max - min
> ```
>

### Documentation problem

It is not good that the user guide lists codes that override Python built-in functions.

This is the only part I happened to find, but others may exist in doc. If so, its should be revised as well.

### Suggested fix for documentation

In this case, `max`/`min` should rename like `max_ts`/`min_ts`.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47606/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47606/timeline,,,,
5,https://api.github.com/repos/pandas-dev/pandas/issues/47605,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47605/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47605/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47605/events,https://github.com/pandas-dev/pandas/pull/47605,1295119659,PR_kwDOAA0YD8465ghB,47605,BUG: df.groupby().resample()[[cols]] without key columns raise KeyError,"{'login': 'GYHHAHA', 'id': 41546976, 'node_id': 'MDQ6VXNlcjQxNTQ2OTc2', 'avatar_url': 'https://avatars.githubusercontent.com/u/41546976?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/GYHHAHA', 'html_url': 'https://github.com/GYHHAHA', 'followers_url': 'https://api.github.com/users/GYHHAHA/followers', 'following_url': 'https://api.github.com/users/GYHHAHA/following{/other_user}', 'gists_url': 'https://api.github.com/users/GYHHAHA/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/GYHHAHA/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/GYHHAHA/subscriptions', 'organizations_url': 'https://api.github.com/users/GYHHAHA/orgs', 'repos_url': 'https://api.github.com/users/GYHHAHA/repos', 'events_url': 'https://api.github.com/users/GYHHAHA/events{/privacy}', 'received_events_url': 'https://api.github.com/users/GYHHAHA/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-07-06T04:44:26Z,2022-07-06T07:20:16Z,,CONTRIBUTOR,,"- [x] closes #47362
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47605/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47605/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47605', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47605', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47605.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47605.patch', 'merged_at': None}"
6,https://api.github.com/repos/pandas-dev/pandas/issues/47604,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47604/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47604/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47604/events,https://github.com/pandas-dev/pandas/issues/47604,1294984836,I_kwDOAA0YD85NL-aE,47604,ENH: Display DataFrame column dtypes (data types) for each variable name when printing,"{'login': 'coatless', 'id': 833642, 'node_id': 'MDQ6VXNlcjgzMzY0Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/833642?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/coatless', 'html_url': 'https://github.com/coatless', 'followers_url': 'https://api.github.com/users/coatless/followers', 'following_url': 'https://api.github.com/users/coatless/following{/other_user}', 'gists_url': 'https://api.github.com/users/coatless/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/coatless/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/coatless/subscriptions', 'organizations_url': 'https://api.github.com/users/coatless/orgs', 'repos_url': 'https://api.github.com/users/coatless/repos', 'events_url': 'https://api.github.com/users/coatless/events{/privacy}', 'received_events_url': 'https://api.github.com/users/coatless/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-06T01:34:00Z,2022-07-06T01:34:00Z,,NONE,,"#### Is your feature request related to a problem?

I wish I could incorporate the data type of each column into the output of the Pandas dataframe when using any print method (with a preference for [`.to_html()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_html.html)). The feature could contain:

- `show_dtypes` bool, default False
  - Display DataFrame column dtypes (data types) for each variable name.

#### Describe the solution you'd like

The current way of displaying Pandas data with HTML gives:

<img width=""271"" alt=""original-pandas-to-html-output"" src=""https://user-images.githubusercontent.com/833642/177447257-cbd8a0b7-2a89-49f4-ac74-da364fa19ff1.png"">

The goal here would be to add a subheader row that incorporates the data type of each column variable from `df.dtypes` output, e.g.

<img width=""275"" alt=""additional-subheader-containing-variable-dtype-information"" src=""https://user-images.githubusercontent.com/833642/177446515-9eb0bc8c-1710-447a-88f2-a04c6c5114e2.png"">


#### API breaking implications

If the feature is turned on by default, then any unit tests that assume a specific output feature would break as a new header row would be required.

#### Describe alternatives you've considered

After the HTML object was saved as a string, I used an adhoc method to add an additional subheader with beautiful soup. The method is a bit cumbersome compared to adding a slight modification into [`pandas/io/formats/html.py`](https://github.com/pandas-dev/pandas/blob/734db4f1fde2566a02b3c7ff661a479b0a71633c/pandas/io/formats/html.py#L378-L394)

#### Additional context

To re-create the screenshot above, please run:

```python
import random
import pandas as pd
import numpy as np
from IPython.core.display import HTML
from bs4 import BeautifulSoup

# Simulate data
mu_o = random.choice([19.7,19.8,19.9,20,20.1,20.2])
std_gen = random.choice([1.3, 1.4, 1.5])
sample_size = random.randint(8, 11)
sample_data =  np.round(np.random.normal(mu_o, std_gen, sample_size), 1)

# Convert data set to pandas
df = pd.DataFrame(data = {
    ""id"": list(range(1, sample_size + 1)),
    ""type"": random.choices([""good"",""okay"",""bad"", ""horrible""], k = sample_size),
    ""vol"": sample_data})

# Name columns
df.columns = ['Subject', 'Type', 'Volume (oz)']

# Adhoc way of creating the desired subheader data
html_subheader_dtype = []
for value in df.dtypes.to_dict().values():
  html_subheader_dtype.append(f'<th> <span style=""color:grey;text-align:left;font-size:.75em""> ({value}) </span> </th>')

# Convert to HTML
html_df = df.to_html(index = False, justify = ""left"")

# Use BeautifulSoup 4 to navigate dom
soup = BeautifulSoup(html_df, ""html.parser"")

# Create new tag for a table row
subheader_dtype_row = soup.new_tag(""tr"")

# Format with beautiful soup
row_dtype_data = BeautifulSoup("""".join(str(x) for x in html_subheader_dtype), ""html.parser"")

# Add new BeautifulSoup object into the subheader element
subheader_dtype_row.contents.append(row_dtype_data)
  
# Adding the subheader into the table object
soup.table.thead.append(subheader_dtype_row)

# Convert from bs4.BeautifulSoup to str
modified_df_html = str(soup)

# Display Table
HTML(modified_df_html)
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47604/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47604/timeline,,,,
7,https://api.github.com/repos/pandas-dev/pandas/issues/47603,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47603/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47603/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47603/events,https://github.com/pandas-dev/pandas/pull/47603,1294888314,PR_kwDOAA0YD8464u7M,47603,Unique test,"{'login': 'srotondo', 'id': 97266896, 'node_id': 'U_kgDOBcws0A', 'avatar_url': 'https://avatars.githubusercontent.com/u/97266896?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/srotondo', 'html_url': 'https://github.com/srotondo', 'followers_url': 'https://api.github.com/users/srotondo/followers', 'following_url': 'https://api.github.com/users/srotondo/following{/other_user}', 'gists_url': 'https://api.github.com/users/srotondo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/srotondo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/srotondo/subscriptions', 'organizations_url': 'https://api.github.com/users/srotondo/orgs', 'repos_url': 'https://api.github.com/users/srotondo/repos', 'events_url': 'https://api.github.com/users/srotondo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/srotondo/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-07-05T23:16:10Z,2022-07-06T00:37:30Z,,CONTRIBUTOR,,"- [ ] closes #22558 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47603/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47603/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47603', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47603', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47603.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47603.patch', 'merged_at': None}"
8,https://api.github.com/repos/pandas-dev/pandas/issues/47602,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47602/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47602/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47602/events,https://github.com/pandas-dev/pandas/pull/47602,1294804051,PR_kwDOAA0YD8464cfj,47602,BUG: Make xticks from _quarterly_finder() line up better,"{'login': 'elidourado', 'id': 68493, 'node_id': 'MDQ6VXNlcjY4NDkz', 'avatar_url': 'https://avatars.githubusercontent.com/u/68493?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/elidourado', 'html_url': 'https://github.com/elidourado', 'followers_url': 'https://api.github.com/users/elidourado/followers', 'following_url': 'https://api.github.com/users/elidourado/following{/other_user}', 'gists_url': 'https://api.github.com/users/elidourado/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/elidourado/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/elidourado/subscriptions', 'organizations_url': 'https://api.github.com/users/elidourado/orgs', 'repos_url': 'https://api.github.com/users/elidourado/repos', 'events_url': 'https://api.github.com/users/elidourado/events{/privacy}', 'received_events_url': 'https://api.github.com/users/elidourado/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-07-05T21:42:50Z,2022-07-05T21:42:50Z,,NONE,,"When I plot a series of quarterly data that spans more than 11 years, my vertical grid lines get placed a year before where they should, i.e., one year before a year that is divisible by the default annual spacing. Changing one line in the _quarterly_finder() function, from +1 to +1970, fixes this for me. Can anyone please confirm the issue and that this fixes it?","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47602/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47602/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47602', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47602', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47602.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47602.patch', 'merged_at': None}"
9,https://api.github.com/repos/pandas-dev/pandas/issues/47601,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47601/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47601/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47601/events,https://github.com/pandas-dev/pandas/pull/47601,1294743336,PR_kwDOAA0YD8464PhX,47601,ENH/TST: Add TestBaseReshaping tests for ArrowExtensionArray,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 69, 'closed_issues': 1079, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-07-06T12:06:59Z', 'due_on': '2022-07-31T07:00:00Z', 'closed_at': None}",0,2022-07-05T20:38:37Z,2022-07-06T00:42:43Z,,MEMBER,,"- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47601/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47601/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47601', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47601', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47601.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47601.patch', 'merged_at': None}"
10,https://api.github.com/repos/pandas-dev/pandas/issues/47600,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47600/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47600/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47600/events,https://github.com/pandas-dev/pandas/pull/47600,1294611744,PR_kwDOAA0YD8463z78,47600,CI: run flake8-pyi with all the other flake8 plugins,"{'login': 'twoertwein', 'id': 6618166, 'node_id': 'MDQ6VXNlcjY2MTgxNjY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/twoertwein', 'html_url': 'https://github.com/twoertwein', 'followers_url': 'https://api.github.com/users/twoertwein/followers', 'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}', 'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions', 'organizations_url': 'https://api.github.com/users/twoertwein/orgs', 'repos_url': 'https://api.github.com/users/twoertwein/repos', 'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}', 'received_events_url': 'https://api.github.com/users/twoertwein/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-07-05T18:07:40Z,2022-07-06T03:05:04Z,,CONTRIBUTOR,,"followup to #47595

@mroeschke ","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47600/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47600/timeline,,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47600', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47600', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47600.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47600.patch', 'merged_at': None}"
11,https://api.github.com/repos/pandas-dev/pandas/issues/47598,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47598/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47598/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47598/events,https://github.com/pandas-dev/pandas/pull/47598,1294298140,PR_kwDOAA0YD8462wob,47598,BUG: `pd.period_range` ignores multiple of `start` frequency.,"{'login': 'jaheba', 'id': 133732, 'node_id': 'MDQ6VXNlcjEzMzczMg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/133732?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jaheba', 'html_url': 'https://github.com/jaheba', 'followers_url': 'https://api.github.com/users/jaheba/followers', 'following_url': 'https://api.github.com/users/jaheba/following{/other_user}', 'gists_url': 'https://api.github.com/users/jaheba/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jaheba/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jaheba/subscriptions', 'organizations_url': 'https://api.github.com/users/jaheba/orgs', 'repos_url': 'https://api.github.com/users/jaheba/repos', 'events_url': 'https://api.github.com/users/jaheba/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jaheba/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-07-05T13:23:43Z,2022-07-05T13:26:44Z,,NONE,,"Fixes: #47465

- [ ] closes #47465
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47598/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47598/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47598', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47598', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47598.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47598.patch', 'merged_at': None}"
12,https://api.github.com/repos/pandas-dev/pandas/issues/47597,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47597/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47597/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47597/events,https://github.com/pandas-dev/pandas/pull/47597,1294043839,PR_kwDOAA0YD846150-,47597,Added improvements in to_datetime Error reporting message,"{'login': 'dannyi96', 'id': 15380498, 'node_id': 'MDQ6VXNlcjE1MzgwNDk4', 'avatar_url': 'https://avatars.githubusercontent.com/u/15380498?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dannyi96', 'html_url': 'https://github.com/dannyi96', 'followers_url': 'https://api.github.com/users/dannyi96/followers', 'following_url': 'https://api.github.com/users/dannyi96/following{/other_user}', 'gists_url': 'https://api.github.com/users/dannyi96/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dannyi96/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dannyi96/subscriptions', 'organizations_url': 'https://api.github.com/users/dannyi96/orgs', 'repos_url': 'https://api.github.com/users/dannyi96/repos', 'events_url': 'https://api.github.com/users/dannyi96/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dannyi96/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3MDk2NQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Error%20Reporting', 'name': 'Error Reporting', 'color': 'ffa0ff', 'default': False, 'description': 'Incorrect or improved errors from pandas'}]",open,False,,[],,2,2022-07-05T09:34:43Z,2022-07-05T17:14:02Z,,CONTRIBUTOR,,"- This PR aims to close 3 related issues - 
#16757 , 
#46509 , 
#47495

- Changes description
    -  For issue #16757 - added more details in error message about field and its position causing the issue in `pandas/_libs/tslib.pyx` in `_array_to_datetime_object` and `array_to_datetime`
    -  For issue #46509 -  added more details in OutOfBoundsDatetime exception about field and its position causing the issue in `pandas/_libs/tslib.pyx` in `array_to_datetime`
    - For issue #47495 - made change in `pandas/_libs/tslibs/parsing.pyx` to accept ""now"" and ""today"" values. These values are accepted in other parts of parsing ( `_parse_today_now` in `pandas/_libs/tslib.pyx` ) but when `pd.to_datetime` is supplied with an list having an error value(eg - `pd.to_datetime([""today"", ""yesterday""])` ), the parsing done post raised exception in `parse_datetime_string` in `pandas/_libs/tslibs/parsing.pyx` does not accept ""now"" and ""today"", hence the wrong element is shown in the error

- Examples of changed error messages


    | Code       | Old Error ( on 1.4.3 ) | New Error |
    | ------------- | ------------- | ------------- |
    | pd.to_datetime(pd.Series(['2016-01-01', 'unparseable']), errors='raise')  | dateutil.parser._parser.ParserError: Unknown string format: unparseable  | ValueError: Unable to parse string ""unparseable"" at position 1 |
    | pd.to_datetime(pd.Series(['2016-01-01', 'unparseable']), format='%Y-%m-%d', errors='raise') | ValueError: time data unparseable doesn't match format specified  | ValueError: time data ""unparseable"" at position 1 doesn't match format specified |
    | pd.to_datetime(pd.Series(['2016-01-01', '12']), errors='raise') | ValueError: Given date string not likely a datetime.  | ValueError: Unable to parse string ""12"" at position 1 |
    | pd.to_datetime('11:0') | pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 11:00:00  | pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Cannot convert ""11:0"" at position 0 to datetime |
    | pd.to_datetime([""today"", ""yesterday""]) | dateutil.parser._parser.ParserError: Unknown string format: today  | ValueError: Unable to parse string ""yesterday"" at position 1 |

**To Do**
- [ ] add testcases covering above errors once given the initial go ahead. ( am bit new here, was thinking of sending the changes in chunks, instead of going more ahead in wrong direction 🙂  )
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47597/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47597/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47597', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47597', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47597.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47597.patch', 'merged_at': None}"
13,https://api.github.com/repos/pandas-dev/pandas/issues/47596,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47596/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47596/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47596/events,https://github.com/pandas-dev/pandas/issues/47596,1293974451,I_kwDOAA0YD85NIHuz,47596,BUG: Inconsistent handling of dropping levels in MultiIndex when using IndexSlice,"{'login': 'mousey92', 'id': 26246536, 'node_id': 'MDQ6VXNlcjI2MjQ2NTM2', 'avatar_url': 'https://avatars.githubusercontent.com/u/26246536?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mousey92', 'html_url': 'https://github.com/mousey92', 'followers_url': 'https://api.github.com/users/mousey92/followers', 'following_url': 'https://api.github.com/users/mousey92/following{/other_user}', 'gists_url': 'https://api.github.com/users/mousey92/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mousey92/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mousey92/subscriptions', 'organizations_url': 'https://api.github.com/users/mousey92/orgs', 'repos_url': 'https://api.github.com/users/mousey92/repos', 'events_url': 'https://api.github.com/users/mousey92/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mousey92/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-05T08:35:28Z,2022-07-05T08:35:28Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
>>>import numpy as np
>>>import pandas as pd
>>>idx = pd.IndexSlice
>>>df = pd.DataFrame(np.random.rand(8, 4),
                     index=pd.MultiIndex.from_product([[""A"", ""B""], range(2), ['a', 'b']]),
                     columns=pd.MultiIndex.from_product([['a', 'b'], range(2)]))
>>>df
              a                   b          
              0         1         0         1
A 0 a  0.791022  0.810915  0.903327  0.623326
    b  0.637121  0.521150  0.036788  0.302978
  1 a  0.491420  0.622780  0.889818  0.859360
    b  0.212784  0.056860  0.562042  0.349412
B 0 a  0.246708  0.522429  0.822344  0.134595
    b  0.219090  0.909012  0.166682  0.601046
  1 a  0.638349  0.458048  0.997902  0.152901
    b  0.294982  0.435510  0.350015  0.961403
>>>df.loc[""A""]  # Drops first level, since selecting with scalar value
            a                   b          
            0         1         0         1
0 a  0.791022  0.810915  0.903327  0.623326
  b  0.637121  0.521150  0.036788  0.302978
1 a  0.491420  0.622780  0.889818  0.859360
  b  0.212784  0.056860  0.562042  0.349412
>>>df.loc[idx[""A"", :, :], :]  # Keeps first level, despite selecting with scalar value in first level
              a                   b          
              0         1         0         1
A 0 a  0.791022  0.810915  0.903327  0.623326
    b  0.637121  0.521150  0.036788  0.302978
  1 a  0.491420  0.622780  0.889818  0.859360
    b  0.212784  0.056860  0.562042  0.349412
>>>df.loc[idx[""A""]]  # Not how I would normally slice, but it is within the realm of possibilities. Scalar value drops level
            a                   b          
            0         1         0         1
0 a  0.791022  0.810915  0.903327  0.623326
  b  0.637121  0.521150  0.036788  0.302978
1 a  0.491420  0.622780  0.889818  0.859360
  b  0.212784  0.056860  0.562042  0.349412
>>>df.loc[idx[""A"", :, :]]  # Slicing on 2 out of 3 levels will keep the level
              a                   b          
              0         1         0         1
A 0 a  0.791022  0.810915  0.903327  0.623326
    b  0.637121  0.521150  0.036788  0.302978
  1 a  0.491420  0.622780  0.889818  0.859360
    b  0.212784  0.056860  0.562042  0.349412
>>>df.loc[idx[""A"", :]]  # Slicing on 1 level will drop the level
            a                   b          
            0         1         0         1
0 a  0.791022  0.810915  0.903327  0.623326
  b  0.637121  0.521150  0.036788  0.302978
1 a  0.491420  0.622780  0.889818  0.859360
  b  0.212784  0.056860  0.562042  0.349412
```


### Issue Description

Not 100% sure this issue has not been reported yet. #10521 seems to discuss the same issue, but in my opinion doesn't generalize the problem well enough.

When selecting from the DataFrame using .loc and a scalar value, the level that scalar value is indexing is dropped. But when selecting the same using IndexSlice, the behaviour is unpredictable (see examples). Depending on which and how much levels are 'sliced' using a scalar, the level of that scalar selection may be dropped, but it is unclear what the rules for this are. Especially since there are some mentions in the documentation and other issues of scalars always dropping the level.

### Expected Behavior

Any index level that is selected using a scalar value from that level should either have the level dropped across index selection tools, or **not** have the level dropped across index selection tools. Either way, it should be consistent.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Netherlands.1252

pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.1.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47596/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47596/timeline,,,,
14,https://api.github.com/repos/pandas-dev/pandas/issues/47593,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47593/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47593/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47593/events,https://github.com/pandas-dev/pandas/issues/47593,1293012269,I_kwDOAA0YD85NEc0t,47593,QST: pd.read_sql how to process with null char '\0',"{'login': 'flyly0755', 'id': 45039060, 'node_id': 'MDQ6VXNlcjQ1MDM5MDYw', 'avatar_url': 'https://avatars.githubusercontent.com/u/45039060?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/flyly0755', 'html_url': 'https://github.com/flyly0755', 'followers_url': 'https://api.github.com/users/flyly0755/followers', 'following_url': 'https://api.github.com/users/flyly0755/following{/other_user}', 'gists_url': 'https://api.github.com/users/flyly0755/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/flyly0755/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/flyly0755/subscriptions', 'organizations_url': 'https://api.github.com/users/flyly0755/orgs', 'repos_url': 'https://api.github.com/users/flyly0755/repos', 'events_url': 'https://api.github.com/users/flyly0755/events{/privacy}', 'received_events_url': 'https://api.github.com/users/flyly0755/received_events', 'type': 'User', 'site_admin': False}","[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-04T11:06:40Z,2022-07-04T11:06:40Z,,NONE,,"### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).


### Link to question on StackOverflow

https://stackoverflow.com/questions/60615623/problem-while-reading-sql-query-in-python-x00-added-after-each-character

### Question about pandas

with  pd.read_sql() method, occur result with null char '\0' show as 口(look like as this, the showed char in the issued page can't show here).
I am not sure it is a bug or not, maybe there is some method to control showed content.
like fillna('') can transfer the None in python to space.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47593/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47593/timeline,,,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/47592,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47592/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47592/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47592/events,https://github.com/pandas-dev/pandas/issues/47592,1292696014,I_kwDOAA0YD85NDPnO,47592,BUG: raised error when converting (`.dt.tz_convert`) a NaT Series,"{'login': 'igonro', 'id': 6860957, 'node_id': 'MDQ6VXNlcjY4NjA5NTc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6860957?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/igonro', 'html_url': 'https://github.com/igonro', 'followers_url': 'https://api.github.com/users/igonro/followers', 'following_url': 'https://api.github.com/users/igonro/following{/other_user}', 'gists_url': 'https://api.github.com/users/igonro/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/igonro/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/igonro/subscriptions', 'organizations_url': 'https://api.github.com/users/igonro/orgs', 'repos_url': 'https://api.github.com/users/igonro/repos', 'events_url': 'https://api.github.com/users/igonro/events{/privacy}', 'received_events_url': 'https://api.github.com/users/igonro/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-07-04T06:33:09Z,2022-07-06T08:06:05Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
>>> df1 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,'2022-07-02T09:45:33Z',np.nan]})
>>> df2 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,np.nan,np.nan]})
>>> pd.to_datetime(df1['resolved'], format=""%Y-%m-%dT%H:%M:%S"", errors=""coerce"").dt.tz_convert(""Europe/Madrid"").dt.tz_localize(None)
0                   NaT
1                   NaT
2                   NaT
3   2022-07-02 11:45:33
4                   NaT
Name: resolved, dtype: datetime64[ns]
>>> pd.to_datetime(df2['resolved'], format=""%Y-%m-%dT%H:%M:%S"", errors=""coerce"").dt.tz_convert(""Europe/Madrid"").dt.tz_localize(None)
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/accessor.py"", line 94, in f
    return self._delegate_method(name, *args, **kwargs)
  File ""/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/accessors.py"", line 123, in _delegate_method
    result = method(*args, **kwargs)
  File ""/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py"", line 268, in tz_convert
    arr = self._data.tz_convert(tz)
  File ""/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py"", line 874, in tz_convert
    raise TypeError(
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize
```


### Issue Description

`.dt.tz_convert` is able to transform a Series with mixed tz-aware datetimes and NaTs, but it raises an error when trying to convert a Series with only NaTs.

I understand that this error should be the expected when having tz-naive datetimes (for example ""2022-07-02 09:45:33"" instead of ""2022-07-02T09:45:33Z""), but when trying to convert a Series of NaTs I think that everyone would expect a Series of NaTs as well.

### Expected Behavior

Expected behaviour:
- **Return a Series of NaT when converting a Series of NaT**

```python
>>> pd.to_datetime(df2['resolved'], format=""%Y-%m-%dT%H:%M:%S"", errors=""coerce"").dt.tz_convert(""Europe/Madrid"")
0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
```

Keep the behaviour of:
- Return a Series of NaT and converted tz datetimes when converting a Series of NaT and tz-aware datetimes.
- Raise `Cannot convert tz-naive timestamps, use tz_localize to localize` error when converting a Series with tz-naive datetimes.

### Installed Versions

<details>

commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 58.0.4
pip              : 21.2.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47592/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47592/timeline,,,,
16,https://api.github.com/repos/pandas-dev/pandas/issues/47587,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47587/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47587/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47587/events,https://github.com/pandas-dev/pandas/pull/47587,1292172196,PR_kwDOAA0YD846v07_,47587,TYP: return values in core/*.py,"{'login': 'twoertwein', 'id': 6618166, 'node_id': 'MDQ6VXNlcjY2MTgxNjY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/twoertwein', 'html_url': 'https://github.com/twoertwein', 'followers_url': 'https://api.github.com/users/twoertwein/followers', 'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}', 'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions', 'organizations_url': 'https://api.github.com/users/twoertwein/orgs', 'repos_url': 'https://api.github.com/users/twoertwein/repos', 'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}', 'received_events_url': 'https://api.github.com/users/twoertwein/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-07-03T00:36:12Z,2022-07-04T15:48:57Z,,CONTRIBUTOR,,This PR is quite a bit larger since many functions needed overloads.,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47587/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47587/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47587', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47587', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47587.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47587.patch', 'merged_at': None}"
17,https://api.github.com/repos/pandas-dev/pandas/issues/47585,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47585/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47585/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47585/events,https://github.com/pandas-dev/pandas/pull/47585,1292157615,PR_kwDOAA0YD846vyHh,47585,BUG: Series map ignoring na_action for dict or series mapper,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-07-02T22:48:26Z,2022-07-05T14:13:21Z,,MEMBER,,"- [x] closes #47527 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47585/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47585/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47585', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47585', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47585.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47585.patch', 'merged_at': None}"
18,https://api.github.com/repos/pandas-dev/pandas/issues/47584,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47584/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47584/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47584/events,https://github.com/pandas-dev/pandas/issues/47584,1292102669,I_kwDOAA0YD85NA-wN,47584,DOC: Indicate `formatters` in `DataFrame.to_string` can specify `__index__`,"{'login': 'ntjess', 'id': 23620506, 'node_id': 'MDQ6VXNlcjIzNjIwNTA2', 'avatar_url': 'https://avatars.githubusercontent.com/u/23620506?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ntjess', 'html_url': 'https://github.com/ntjess', 'followers_url': 'https://api.github.com/users/ntjess/followers', 'following_url': 'https://api.github.com/users/ntjess/following{/other_user}', 'gists_url': 'https://api.github.com/users/ntjess/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ntjess/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ntjess/subscriptions', 'organizations_url': 'https://api.github.com/users/ntjess/orgs', 'repos_url': 'https://api.github.com/users/ntjess/repos', 'events_url': 'https://api.github.com/users/ntjess/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ntjess/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-07-02T17:30:55Z,2022-07-02T17:35:49Z,,NONE,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_string.html?highlight=formatters

### Documentation problem

The current  [`to_string`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_string.html?highlight=formatters) documentation for `formatters` indicates formatting can be applied to columns, but it is unclear whether anything can be set for the index as well. Deep within [`format.py`](https://github.com/pandas-dev/pandas/blob/main/pandas/io/formats/format.py#L962), it appears adding an `__index__` key to formatters will handle this well. I tested with the code below which seemed to work:

```python
import pandas as pd
fmt = ""{:.4f}"".format
fmt_dict = dict(__index__=fmt)
print(pd.DataFrame([[1,2,3]]).to_string(formatters=fmt_dict))
```

Is this feature meant to be public? If so, I would recommend exposing it in the `formatters` parameter description. Thanks!

### Suggested fix for documentation

New `formatters` description resembling the following. Added sentence is italicized:

Formatter functions to apply to columns’ elements by position or name. The result of each function must be a unicode string. List/tuple must be of length equal to the number of columns. *If a dict-like formatter is specified, the dataframe's index can be formatted with an `__index__` key.*

---

Alternatively, the MWE in this issue (or something similar) can be added to the `Examples` section.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47584/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47584/timeline,,,,
19,https://api.github.com/repos/pandas-dev/pandas/issues/47582,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47582/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47582/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47582/events,https://github.com/pandas-dev/pandas/issues/47582,1292041116,I_kwDOAA0YD85NAvuc,47582,BUG: loc aligning rhs with list indexer but not with scalar,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-02T12:04:06Z,2022-07-02T12:04:13Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
result = pd.DataFrame({""var"": [1, 2]}, index=[1, 2])

rhs = pd.DataFrame({""a"": [10, 11]}, index=[2, 3])

result.loc[:, [""var""]] = rhs

This aligns the column names and hence returns

   var
1  NaN
2  NaN

while

result = pd.DataFrame({""var"": [1, 2]}, index=[1, 2])

rhs = pd.DataFrame({""a"": [10, 11]}, index=[2, 3])

result.loc[:, ""var""] = rhs

returns 

    var
1   NaN
2  10.0

after #47578 is fixed. currently this returns

    var
1   10
2   10
```


### Issue Description

Both cases should be consistent, I think both of them should align

cc @jbrockmendel 

### Expected Behavior

Both align

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47582/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47582/timeline,,,,
20,https://api.github.com/repos/pandas-dev/pandas/issues/47577,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47577/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47577/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47577/events,https://github.com/pandas-dev/pandas/issues/47577,1291881775,I_kwDOAA0YD85NAI0v,47577,BUG: Setting incompatible values into ea column raises instead of casting to object,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 1817503692, 'node_id': 'MDU6TGFiZWwxODE3NTAzNjky', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays', 'name': 'NA - MaskedArrays', 'color': '8cc645', 'default': False, 'description': 'Related to pd.NA and nullable extension arrays'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-01T22:26:06Z,2022-07-01T22:26:38Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
ser = pd.Series([1, 2], dtype=""Int64"")
ser[1] = ""a""

This raises, while expanding casts to object

ser = pd.Series([1, 2], dtype=""Int64"")
ser[2] = ""a""
```


### Issue Description

Numpy dtypes are casting to object while ea dtypes raise. Was this a deliberate descision?

cc @jorisvandenbossche 

### Expected Behavior

I would probably expect this to work.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 55d9dcf47dd982248c18237b6a09854ea83bc474
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-40-generic
Version          : #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+1066.g55d9dcf47d
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.3.2
pip              : 22.1.2
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.47.0
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.1
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.2
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : 1.1.7
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.1
snappy           : 
sqlalchemy       : 1.4.37
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47577/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47577/timeline,,,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/47576,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47576/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47576/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47576/events,https://github.com/pandas-dev/pandas/issues/47576,1291879073,I_kwDOAA0YD85NAIKh,47576,"BUG: Spurious ""FutureWarning: Use pd.to_datetime instead.""","{'login': 'lafrech', 'id': 1767010, 'node_id': 'MDQ6VXNlcjE3NjcwMTA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1767010?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lafrech', 'html_url': 'https://github.com/lafrech', 'followers_url': 'https://api.github.com/users/lafrech/followers', 'following_url': 'https://api.github.com/users/lafrech/following{/other_user}', 'gists_url': 'https://api.github.com/users/lafrech/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lafrech/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lafrech/subscriptions', 'organizations_url': 'https://api.github.com/users/lafrech/orgs', 'repos_url': 'https://api.github.com/users/lafrech/repos', 'events_url': 'https://api.github.com/users/lafrech/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lafrech/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,3,2022-07-01T22:20:14Z,2022-07-01T22:48:52Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import io
import datetime as dt

import pandas as pd


csv_file = io.StringIO(""Timestamp,Value\n2020-01-01T00:00:00,12"")

def to_aware_datetime(timestamp_str):
    timestamp_dt = pd.to_datetime(timestamp_str)
    if timestamp_dt.tzinfo is None:
        raise Exception(""Timestamps must be TZ-aware"")
    return timestamp_dt.astimezone(dt.timezone.utc)

data_df = pd.read_csv(
    csv_file,
    index_col=0,
    parse_dates=True,
    date_parser=to_aware_datetime,
)
```


### Issue Description

A warning is raised:

```
test.py:16: FutureWarning: 
        Use pd.to_datetime instead.
```

I think the root cause is that while trying to support several different use cases, `converter` (in base_parser.py) catches `Exception` a bit too broadly without letting user-generated exceptions bubble-up, until it defaults to calling deprecated `generic_parser` which causes the warning.

I guess `Exception` was used because it was complicated to list all possible exceptions. Beside, even if a more selective list was used, user exceptions derived from exceptions in that list would be caught anyway, so the issue is inherent to the trial and error pattern.

The problem may disappear when `generic_parser` is removed and the last exception is not caught.

The point is that I had a hard time finding out the cause of the warning (and I'm still not even sure I finally understood).

### Expected Behavior

No deprecation warning.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-15-amd64
Version          : #1 SMP Debian 5.10.120-1 (2022-06-09)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.4.3
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 57.4.0
pip              : 22.1.2
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.32
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47576/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47576/timeline,,,,
22,https://api.github.com/repos/pandas-dev/pandas/issues/47571,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47571/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47571/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47571/events,https://github.com/pandas-dev/pandas/issues/47571,1291627218,I_kwDOAA0YD85M_KrS,47571,ENH: dataframe.astype() exception message to include column name,"{'login': 'd3bgger', 'id': 1158542, 'node_id': 'MDQ6VXNlcjExNTg1NDI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1158542?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/d3bgger', 'html_url': 'https://github.com/d3bgger', 'followers_url': 'https://api.github.com/users/d3bgger/followers', 'following_url': 'https://api.github.com/users/d3bgger/following{/other_user}', 'gists_url': 'https://api.github.com/users/d3bgger/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/d3bgger/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/d3bgger/subscriptions', 'organizations_url': 'https://api.github.com/users/d3bgger/orgs', 'repos_url': 'https://api.github.com/users/d3bgger/repos', 'events_url': 'https://api.github.com/users/d3bgger/events{/privacy}', 'received_events_url': 'https://api.github.com/users/d3bgger/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-07-01T16:54:21Z,2022-07-01T16:54:21Z,,NONE,,"#### Is your feature request related to a problem?

When using dataframe.astype() and there is a column missing or there are some values that cannot be correctly converted, there is an exception raised. But there is no way to know which column is missing or which column has the wrong value.

#### Describe the solution you'd like

The exception message of the dataframe.astype() should contain the column name responsible for the exception (missing column(s) or column with wrong values).

#### API breaking implications

This does not introduce any breaking changes

#### Additional context

Some examples of the current exceptions raised by astype():

```
KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'

TypeError: object cannot be converted to an IntegerDtype

ValueError: invalid literal for int() with base 10: 'test'
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47571/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47571/timeline,,,,
23,https://api.github.com/repos/pandas-dev/pandas/issues/47570,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47570/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47570/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47570/events,https://github.com/pandas-dev/pandas/pull/47570,1291503075,PR_kwDOAA0YD846tqo9,47570,"BUG: Fixed `tm.set_locale` context manager, it could error and leak when category LC_ALL was used","{'login': 'smarie', 'id': 3236794, 'node_id': 'MDQ6VXNlcjMyMzY3OTQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3236794?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/smarie', 'html_url': 'https://github.com/smarie', 'followers_url': 'https://api.github.com/users/smarie/followers', 'following_url': 'https://api.github.com/users/smarie/following{/other_user}', 'gists_url': 'https://api.github.com/users/smarie/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/smarie/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/smarie/subscriptions', 'organizations_url': 'https://api.github.com/users/smarie/orgs', 'repos_url': 'https://api.github.com/users/smarie/repos', 'events_url': 'https://api.github.com/users/smarie/events{/privacy}', 'received_events_url': 'https://api.github.com/users/smarie/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,2,2022-07-01T14:47:13Z,2022-07-06T12:25:34Z,,CONTRIBUTOR,,"
- [x] closes #46595
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47570/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47570/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47570', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47570', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47570.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47570.patch', 'merged_at': None}"
24,https://api.github.com/repos/pandas-dev/pandas/issues/47569,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47569/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47569/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47569/events,https://github.com/pandas-dev/pandas/issues/47569,1291413614,I_kwDOAA0YD85M-Whu,47569,"CI 1.4.x: Typing error Overload 2 for ""searchsorted"" will never be used because its parameters overlap overload 1","{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}, {'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/96', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96/labels', 'id': 8104401, 'node_id': 'MI_kwDOAA0YD84Ae6nR', 'number': 96, 'title': '1.4.4', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 31, 'closed_issues': 16, 'state': 'open', 'created_at': '2022-06-21T19:44:05Z', 'updated_at': '2022-07-06T00:29:20Z', 'due_on': '2022-07-31T07:00:00Z', 'closed_at': None}",2,2022-07-01T13:28:24Z,2022-07-02T16:48:11Z,,MEMBER,,See https://github.com/pandas-dev/pandas/runs/7029429387?check_suite_focus=true,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47569/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47569/timeline,,,,
25,https://api.github.com/repos/pandas-dev/pandas/issues/47564,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47564/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47564/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47564/events,https://github.com/pandas-dev/pandas/pull/47564,1291005009,PR_kwDOAA0YD846r-yY,47564,⬆️ UPGRADE: Autoupdate pre-commit config,"{'login': 'github-actions[bot]', 'id': 41898282, 'node_id': 'MDM6Qm90NDE4OTgyODI=', 'avatar_url': 'https://avatars.githubusercontent.com/in/15368?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions%5Bbot%5D', 'html_url': 'https://github.com/apps/github-actions', 'followers_url': 'https://api.github.com/users/github-actions%5Bbot%5D/followers', 'following_url': 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}', 'gists_url': 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions', 'organizations_url': 'https://api.github.com/users/github-actions%5Bbot%5D/orgs', 'repos_url': 'https://api.github.com/users/github-actions%5Bbot%5D/repos', 'events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}', 'received_events_url': 'https://api.github.com/users/github-actions%5Bbot%5D/received_events', 'type': 'Bot', 'site_admin': False}",[],open,False,,[],,0,2022-07-01T07:08:08Z,2022-07-05T17:22:24Z,,CONTRIBUTOR,,"<!-- START pr-commits -->
<!-- END pr-commits -->

## Base PullRequest

default branch (https://github.com/pandas-dev/pandas/tree/main)

## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>add path</em></summary>

```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/build/src/bin
```



</details>
<details>
<summary><em>pip install pre-commit</em></summary>

```Shell
Collecting pre-commit
  Downloading pre_commit-2.19.0-py2.py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 9.2 MB/s eta 0:00:00
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.15.1-py2.py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 107.9 MB/s eta 0:00:00
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 99.2 MB/s eta 0:00:00
Collecting identify>=1.0.0
  Downloading identify-2.5.1-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 35.2 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages (from nodeenv>=0.11.1->pre-commit) (58.1.0)
Collecting six<2,>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.2/461.2 kB 89.3 MB/s eta 0:00:00
Collecting filelock<4,>=3.2
  Downloading filelock-3.7.1-py3-none-any.whl (10 kB)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Installing collected packages: distlib, toml, six, pyyaml, platformdirs, nodeenv, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.3.1 distlib-0.3.4 filelock-3.7.1 identify-2.5.1 nodeenv-1.7.0 platformdirs-2.5.2 pre-commit-2.19.0 pyyaml-6.0 six-1.16.0 toml-0.10.2 virtualenv-20.15.1
```



</details>
<details>
<summary><em>pre-commit autoupdate || (exit 0);</em></summary>

```Shell
Updating https://github.com/MarcoGorelli/absolufy-imports ... [INFO] Initializing environment for https://github.com/MarcoGorelli/absolufy-imports.
already up to date.
Updating https://github.com/jendrikseipp/vulture ... [INFO] Initializing environment for https://github.com/jendrikseipp/vulture.
already up to date.
Updating https://github.com/python/black ... [INFO] Initializing environment for https://github.com/python/black.
updating 22.3.0 -> 22.6.0.
Updating https://github.com/codespell-project/codespell ... [INFO] Initializing environment for https://github.com/codespell-project/codespell.
already up to date.
Updating https://github.com/pre-commit/pre-commit-hooks ... [INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
updating v4.2.0 -> v4.3.0.
Updating https://github.com/cpplint/cpplint ... [INFO] Initializing environment for https://github.com/cpplint/cpplint.
already up to date.
Updating https://github.com/PyCQA/flake8 ... [INFO] Initializing environment for https://github.com/PyCQA/flake8.
already up to date.
Updating https://github.com/PyCQA/isort ... [INFO] Initializing environment for https://github.com/PyCQA/isort.
already up to date.
Updating https://github.com/asottile/pyupgrade ... [INFO] Initializing environment for https://github.com/asottile/pyupgrade.
updating v2.32.1 -> v2.34.0.
Updating https://github.com/pre-commit/pygrep-hooks ... [INFO] Initializing environment for https://github.com/pre-commit/pygrep-hooks.
already up to date.
Updating https://github.com/sphinx-contrib/sphinx-lint ... [INFO] Initializing environment for https://github.com/sphinx-contrib/sphinx-lint.
updating v0.6 -> v0.6.1.
Updating https://github.com/asottile/yesqa ... [INFO] Initializing environment for https://github.com/asottile/yesqa.
already up to date.
```



</details>
<details>
<summary><em>pre-commit run -a || (exit 0);</em></summary>

```Shell
[INFO] Initializing environment for https://github.com/PyCQA/flake8:flake8-bugbear==21.3.2,flake8-comprehensions==3.7.0,flake8==4.0.1,pandas-dev-flaker==0.5.0.
[INFO] Initializing environment for https://github.com/asottile/yesqa:flake8-bugbear==21.3.2,flake8-comprehensions==3.7.0,flake8==4.0.1,pandas-dev-flaker==0.5.0.
[INFO] Initializing environment for local:pyright@1.1.253.
[INFO] Initializing environment for local:flake8-rst==0.7.0,flake8==3.7.9.
[INFO] Initializing environment for local:pyyaml,toml.
[INFO] Initializing environment for local:pyyaml.
[INFO] Initializing environment for local.
[INFO] Installing environment for https://github.com/MarcoGorelli/absolufy-imports.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/jendrikseipp/vulture.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/python/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/codespell-project/codespell.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/cpplint/cpplint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/sphinx-contrib/sphinx-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/yesqa.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
absolufy-imports........................................................................................Passed
vulture.................................................................................................Passed
black...................................................................................................Passed
codespell...............................................................................................Passed
debug statements (python)...............................................................................Passed
fix end of files........................................................................................Passed
trim trailing whitespace................................................................................Passed
cpplint.................................................................................................Passed
flake8..................................................................................................Passed
isort...................................................................................................Passed
pyupgrade...............................................................................................Passed
rst ``code`` is two backticks...........................................................................Passed
rst directives end with two colons......................................................................Passed
rst ``inline code`` next to normal text.................................................................Passed
Sphinx lint.............................................................................................Passed
Strip unnecessary `# noqa`s.............................................................................Passed
flake8-rst..............................................................................................Failed
- hook id: flake8-rst
- exit code: 1

Traceback (most recent call last):
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 486, in run_ast_checks
    ast = self.processor.build_ast()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/processor.py"", line 212, in build_ast
    return compile("""".join(self.lines), """", ""exec"", PyCF_ONLY_AST)
  File """", line 27
    df2.<TAB>  # noqa: E225, E999
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/bin/flake8-rst"", line 8, in <module>
    sys.exit(main())
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8_rst/cli.py"", line 16, in main
    app.run(argv)
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/main/application.py"", line 393, in run
    self._run(argv)
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/main/application.py"", line 381, in _run
    self.run_checks()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/main/application.py"", line 300, in run_checks
    self.file_checker_manager.run()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 331, in run
    self.run_serial()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 315, in run_serial
    checker.run_checks()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 598, in run_checks
    self.run_ast_checks()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 488, in run_ast_checks
    row, column = self._extract_syntax_information(e)
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 473, in _extract_syntax_information
    lines = physical_line.rstrip(""\n"").split(""\n"")
AttributeError: 'int' object has no attribute 'rstrip'
Traceback (most recent call last):
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 486, in run_ast_checks
    ast = self.processor.build_ast()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/processor.py"", line 212, in build_ast
    return compile("""".join(self.lines), """", ""exec"", PyCF_ONLY_AST)
  File """", line 203
    df.foo<TAB>  # noqa: E225, E999
                 ^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/bin/flake8-rst"", line 8, in <module>
    sys.exit(main())
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8_rst/cli.py"", line 16, in main
    app.run(argv)
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/main/application.py"", line 393, in run
    self._run(argv)
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/main/application.py"", line 381, in _run
    self.run_checks()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/main/application.py"", line 300, in run_checks
    self.file_checker_manager.run()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 331, in run
    self.run_serial()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 315, in run_serial
    checker.run_checks()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 598, in run_checks
    self.run_ast_checks()
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 488, in run_ast_checks
    row, column = self._extract_syntax_information(e)
  File ""/home/runner/.cache/pre-commit/repoqgu3q7dm/py_env-python3.10/lib/python3.10/site-packages/flake8/checker.py"", line 473, in _extract_syntax_information
    lines = physical_line.rstrip(""\n"").split(""\n"")
AttributeError: 'int' object has no attribute 'rstrip'

Unwanted patterns.......................................................................................Passed
Check Cython casting is `<type>obj`, not `<type> obj`...................................................Passed
Check for backticks incorrectly rendering because of missing spaces.....................................Passed
Check for unnecessary random seeds in asv benchmarks....................................................Passed
Check for usage of numpy testing or array_equal.........................................................Passed
Check for invalid EA testing............................................................................Passed
Generate pip dependency from conda......................................................................Passed
Check flake8 version is synced across flake8, yesqa, and environment.yml................................Passed
Validate correct capitalization among titles in documentation...........................................Passed
Import pandas.array as pd_array in core.................................................................Passed
Use pandas.io.common.urlopen instead of urllib.request.urlopen..........................................Passed
Use bool_t instead of bool in pandas/core/generic.py....................................................Passed
Ensure pandas errors are documented in doc/source/reference/testing.rst.................................Passed
Check for pg8000 not installed on CI for test_pg8000_sqlalchemy_passthrough_error.......................Passed
Check minimum version of dependencies are aligned.......................................................Passed
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- .pre-commit-config.yaml

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/create-pr-action)","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47564/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47564/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47564', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47564', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47564.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47564.patch', 'merged_at': None}"
26,https://api.github.com/repos/pandas-dev/pandas/issues/47563,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47563/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47563/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47563/events,https://github.com/pandas-dev/pandas/issues/47563,1290946951,I_kwDOAA0YD85M8kmH,47563,BUG: plot option sort_columns doesn't work,"{'login': 'PorcelainMouse', 'id': 159714, 'node_id': 'MDQ6VXNlcjE1OTcxNA==', 'avatar_url': 'https://avatars.githubusercontent.com/u/159714?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/PorcelainMouse', 'html_url': 'https://github.com/PorcelainMouse', 'followers_url': 'https://api.github.com/users/PorcelainMouse/followers', 'following_url': 'https://api.github.com/users/PorcelainMouse/following{/other_user}', 'gists_url': 'https://api.github.com/users/PorcelainMouse/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/PorcelainMouse/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/PorcelainMouse/subscriptions', 'organizations_url': 'https://api.github.com/users/PorcelainMouse/orgs', 'repos_url': 'https://api.github.com/users/PorcelainMouse/repos', 'events_url': 'https://api.github.com/users/PorcelainMouse/events{/privacy}', 'received_events_url': 'https://api.github.com/users/PorcelainMouse/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzMzI4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Visualization', 'name': 'Visualization', 'color': '8AE234', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-07-01T05:58:50Z,2022-07-06T05:37:59Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import numpy as np
import pandas as pd
df1 = pd.DataFrame({
    'a' : np.random.normal(0,1,10),
    'b' : np.random.normal(0,1,10),
)}
df1[['b','a']].plot.box(sort_columns=True)
df1[['b','a']].sort_index(axis=1).plot.box()
```


### Issue Description

Best I can tell, this option just doesn't work.  The documentation describes the result of this option as ""Sort column names to determine plot ordering.""  It is clear this means ordering the columns by name, presumably lexically.  But, instead, this is what it does:
![bug_python_sort](https://user-images.githubusercontent.com/159714/176798335-3d8ad908-f539-4cc6-810e-b499d71dbcb6.png)

### Expected Behavior

I interpret this option to be equivalent to .sort_index(axis=1), which works.

![bug_python_sort_workaround](https://user-images.githubusercontent.com/159714/176798439-86e8d98b-572d-4573-935c-b1078256ef71.png)


### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.18.6-200.fc36.x86_64
Version          : #1 SMP PREEMPT_DYNAMIC Wed Jun 22 13:46:18 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.utf8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.0
pytz             : 2022.1
dateutil         : 2.8.1
setuptools       : 59.6.0
pip              : 21.3.1
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.4.0
blosc            : 1.10.6
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: 0.10.0
bs4              : 4.11.0
bottleneck       : 1.3.2
brotli           : 1.0.9
fastparquet      : 0.8.1
fsspec           : 2022.5.0
gcsfs            : 2022.5.0
markupsafe       : 2.0.0
matplotlib       : 3.5.2
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.39
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47563/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47563/timeline,,,,
27,https://api.github.com/repos/pandas-dev/pandas/issues/47557,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47557/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47557/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47557/events,https://github.com/pandas-dev/pandas/pull/47557,1290756094,PR_kwDOAA0YD846rJ9C,47557,ENH: RangeIndex._shallow_copy can return RangeIndex,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMjE4MjI3MzEw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Index', 'name': 'Index', 'color': 'e99695', 'default': False, 'description': 'Related to the Index class or subclasses'}]",open,False,,[],,0,2022-07-01T00:17:47Z,2022-07-05T22:45:28Z,,MEMBER,,"- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Could close https://github.com/pandas-dev/pandas/issues/46675 but in a non-backward-compat way.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47557/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47557/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47557', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47557', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47557.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47557.patch', 'merged_at': None}"
28,https://api.github.com/repos/pandas-dev/pandas/issues/47554,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47554/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47554/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47554/events,https://github.com/pandas-dev/pandas/issues/47554,1290039010,I_kwDOAA0YD85M5G7i,47554,"BUG: Series with same index values, but in different orders, cannot be compared, but can be added","{'login': 'Dr-Irv', 'id': 15113894, 'node_id': 'MDQ6VXNlcjE1MTEzODk0', 'avatar_url': 'https://avatars.githubusercontent.com/u/15113894?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Dr-Irv', 'html_url': 'https://github.com/Dr-Irv', 'followers_url': 'https://api.github.com/users/Dr-Irv/followers', 'following_url': 'https://api.github.com/users/Dr-Irv/following{/other_user}', 'gists_url': 'https://api.github.com/users/Dr-Irv/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Dr-Irv/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Dr-Irv/subscriptions', 'organizations_url': 'https://api.github.com/users/Dr-Irv/orgs', 'repos_url': 'https://api.github.com/users/Dr-Irv/repos', 'events_url': 'https://api.github.com/users/Dr-Irv/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Dr-Irv/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 47223669, 'node_id': 'MDU6TGFiZWw0NzIyMzY2OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Numeric%20Operations', 'name': 'Numeric Operations', 'color': '006b75', 'default': False, 'description': 'Arithmetic, Comparison, and Logical operations'}, {'id': 1357732944, 'node_id': 'MDU6TGFiZWwxMzU3NzMyOTQ0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Series', 'name': 'Series', 'color': '8dd5fc', 'default': False, 'description': 'Series data structure'}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-06-30T12:07:01Z,2022-07-02T20:47:51Z,,CONTRIBUTOR,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
s=pd.Series([1,2,3,4,5])
s
t=s[-1::-1]
t
s + t
s <= t
```


### Issue Description

Code above produces
```
>>> import pandas as pd
>>> s=pd.Series([1,2,3,4,5])
>>> s
0    1
1    2
2    3
3    4
4    5
dtype: int64
>>> t=s[-1::-1]
>>> t
4    5
3    4
2    3
1    2
0    1
dtype: int64
>>> s + t
0     2
1     4
2     6
3     8
4    10
dtype: int64
>>> s <= t
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\ops\common.py"", line 70, in new_method
    return method(self, other)
  File ""C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\arraylike.py"", line 52, in __le__
    return self._cmp_method(other, operator.le)
  File ""C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\series.py"", line 5617, in _cmp_method
    raise ValueError(""Can only compare identically-labeled Series objects"")
ValueError: Can only compare identically-labeled Series objects
```

### Expected Behavior

`s<=t` should produce
```
0    True
1    True
2    True
3    True
4    True
dtype: bool
```

Question is why we align the indices in arithmetic, but not in a logical operation.  The two series are identically labeled, but just not in the same order, so the error message is misleading.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : f4ca4d3d0ea6a907262f8c842c691115b13d4cb7
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.0.dev0+1050.gf4ca4d3d0e
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 60.9.3
pip              : 22.0.3
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.46.11
sphinx           : 4.3.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           :
fastparquet      : 0.8.1
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.1
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : 1.1.7
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.1
snappy           :
sqlalchemy       : 1.4.37
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47554/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47554/timeline,,,,
29,https://api.github.com/repos/pandas-dev/pandas/issues/47550,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/47550/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/47550/comments,https://api.github.com/repos/pandas-dev/pandas/issues/47550/events,https://github.com/pandas-dev/pandas/pull/47550,1288978436,PR_kwDOAA0YD846lLJG,47550,REGR: Ignore eval inplace,"{'login': 'CloseChoice', 'id': 31857876, 'node_id': 'MDQ6VXNlcjMxODU3ODc2', 'avatar_url': 'https://avatars.githubusercontent.com/u/31857876?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/CloseChoice', 'html_url': 'https://github.com/CloseChoice', 'followers_url': 'https://api.github.com/users/CloseChoice/followers', 'following_url': 'https://api.github.com/users/CloseChoice/following{/other_user}', 'gists_url': 'https://api.github.com/users/CloseChoice/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/CloseChoice/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/CloseChoice/subscriptions', 'organizations_url': 'https://api.github.com/users/CloseChoice/orgs', 'repos_url': 'https://api.github.com/users/CloseChoice/repos', 'events_url': 'https://api.github.com/users/CloseChoice/events{/privacy}', 'received_events_url': 'https://api.github.com/users/CloseChoice/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1631985267, 'node_id': 'MDU6TGFiZWwxNjMxOTg1MjY3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/expressions', 'name': 'expressions', 'color': 'f3afff', 'default': False, 'description': 'pd.eval, query'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/96', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/96/labels', 'id': 8104401, 'node_id': 'MI_kwDOAA0YD84Ae6nR', 'number': 96, 'title': '1.4.4', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 31, 'closed_issues': 16, 'state': 'open', 'created_at': '2022-06-21T19:44:05Z', 'updated_at': '2022-07-06T00:29:20Z', 'due_on': '2022-07-31T07:00:00Z', 'closed_at': None}",3,2022-06-29T16:32:14Z,2022-07-03T08:09:10Z,,MEMBER,,"- [x] closes #47449
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

The bad commit that causes this issue (see https://github.com/pandas-dev/pandas/pull/43406) is the rootcause for multiple others, so am not sure if we want to tackle the overall problem bit by bit or if there is a generic solution to all of them.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/47550/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/47550/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/47550', 'html_url': 'https://github.com/pandas-dev/pandas/pull/47550', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/47550.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/47550.patch', 'merged_at': None}"
